[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$ZAwBAMAYo1QqRej9X6u11g$Ccfyq8ZwbMxMowWobQuu3sOw51lrOAh04PJbNb/g76vNB2fMaBhT6LOoaW/zHjhCNbkBzhXNXSSnHqmUHB65IA

